/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiModulesRouteImport } from './routes/ai-modules'
import { Route as AppRouteImport } from './routes/app'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminCropsRouteImport } from './routes/admin.crops'
import { Route as AdminDiseaseRouteImport } from './routes/admin.disease'
import { Route as AdminFarmsRouteImport } from './routes/admin.farms'
import { Route as AdminMarketsRouteImport } from './routes/admin.markets'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminRecommendationsRouteImport } from './routes/admin.recommendations'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSchemesRouteImport } from './routes/admin.schemes'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppCropsRouteImport } from './routes/app.crops'
import { Route as AppDiseaseRouteImport } from './routes/app.disease'
import { Route as AppFarmRouteImport } from './routes/app.farm'
import { Route as AppFieldsRouteImport } from './routes/app.fields'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppMarketRouteImport } from './routes/app.market'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppRecommendationsRouteImport } from './routes/app.recommendations'
import { Route as AppSchemesRouteImport } from './routes/app.schemes'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppWeatherRouteImport } from './routes/app.weather'
import { Route as AppFarmIndexRouteImport } from './routes/app.farm.index'
import { Route as AppFarmFarmIdRouteImport } from './routes/app.farm.$farmId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiModulesRoute = AiModulesRouteImport.update({
  id: '/ai-modules',
  path: '/ai-modules',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCropsRoute = AdminCropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiseaseRoute = AdminDiseaseRouteImport.update({
  id: '/disease',
  path: '/disease',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFarmsRoute = AdminFarmsRouteImport.update({
  id: '/farms',
  path: '/farms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketsRoute = AdminMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecommendationsRoute = AdminRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchemesRoute = AdminSchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppCropsRoute = AppCropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => AppRoute,
} as any)
const AppDiseaseRoute = AppDiseaseRouteImport.update({
  id: '/disease',
  path: '/disease',
  getParentRoute: () => AppRoute,
} as any)
const AppFarmRoute = AppFarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => AppRoute,
} as any)
const AppFieldsRoute = AppFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppSchemesRoute = AppSchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWeatherRoute = AppWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AppRoute,
} as any)
const AppFarmIndexRoute = AppFarmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFarmRoute,
} as any)
const AppFarmFarmIdRoute = AppFarmFarmIdRouteImport.update({
  id: '/$farmId',
  path: '/$farmId',
  getParentRoute: () => AppFarmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-modules': typeof AiModulesRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/crops': typeof AdminCropsRoute
  '/admin/disease': typeof AdminDiseaseRoute
  '/admin/farms': typeof AdminFarmsRoute
  '/admin/markets': typeof AdminMarketsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schemes': typeof AdminSchemesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/crops': typeof AppCropsRoute
  '/app/disease': typeof AppDiseaseRoute
  '/app/farm': typeof AppFarmRouteWithChildren
  '/app/fields': typeof AppFieldsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/market': typeof AppMarketRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/schemes': typeof AppSchemesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/weather': typeof AppWeatherRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/farm/$farmId': typeof AppFarmFarmIdRoute
  '/app/farm/': typeof AppFarmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/ai-modules': typeof AiModulesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/crops': typeof AdminCropsRoute
  '/admin/disease': typeof AdminDiseaseRoute
  '/admin/farms': typeof AdminFarmsRoute
  '/admin/markets': typeof AdminMarketsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schemes': typeof AdminSchemesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/crops': typeof AppCropsRoute
  '/app/disease': typeof AppDiseaseRoute
  '/app/fields': typeof AppFieldsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/market': typeof AppMarketRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/schemes': typeof AppSchemesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/weather': typeof AppWeatherRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/app/farm/$farmId': typeof AppFarmFarmIdRoute
  '/app/farm': typeof AppFarmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-modules': typeof AiModulesRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/crops': typeof AdminCropsRoute
  '/admin/disease': typeof AdminDiseaseRoute
  '/admin/farms': typeof AdminFarmsRoute
  '/admin/markets': typeof AdminMarketsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schemes': typeof AdminSchemesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/crops': typeof AppCropsRoute
  '/app/disease': typeof AppDiseaseRoute
  '/app/farm': typeof AppFarmRouteWithChildren
  '/app/fields': typeof AppFieldsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/market': typeof AppMarketRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/schemes': typeof AppSchemesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/weather': typeof AppWeatherRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/farm/$farmId': typeof AppFarmFarmIdRoute
  '/app/farm/': typeof AppFarmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/admin'
    | '/ai-modules'
    | '/app'
    | '/contact'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/audit-logs'
    | '/admin/crops'
    | '/admin/disease'
    | '/admin/farms'
    | '/admin/markets'
    | '/admin/notifications'
    | '/admin/recommendations'
    | '/admin/reports'
    | '/admin/schemes'
    | '/admin/settings'
    | '/admin/users'
    | '/app/assistant'
    | '/app/crops'
    | '/app/disease'
    | '/app/farm'
    | '/app/fields'
    | '/app/history'
    | '/app/market'
    | '/app/notifications'
    | '/app/profile'
    | '/app/recommendations'
    | '/app/schemes'
    | '/app/settings'
    | '/app/weather'
    | '/admin/'
    | '/app/'
    | '/app/farm/$farmId'
    | '/app/farm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/ai-modules'
    | '/contact'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/audit-logs'
    | '/admin/crops'
    | '/admin/disease'
    | '/admin/farms'
    | '/admin/markets'
    | '/admin/notifications'
    | '/admin/recommendations'
    | '/admin/reports'
    | '/admin/schemes'
    | '/admin/settings'
    | '/admin/users'
    | '/app/assistant'
    | '/app/crops'
    | '/app/disease'
    | '/app/fields'
    | '/app/history'
    | '/app/market'
    | '/app/notifications'
    | '/app/profile'
    | '/app/recommendations'
    | '/app/schemes'
    | '/app/settings'
    | '/app/weather'
    | '/admin'
    | '/app'
    | '/app/farm/$farmId'
    | '/app/farm'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/admin'
    | '/ai-modules'
    | '/app'
    | '/contact'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/audit-logs'
    | '/admin/crops'
    | '/admin/disease'
    | '/admin/farms'
    | '/admin/markets'
    | '/admin/notifications'
    | '/admin/recommendations'
    | '/admin/reports'
    | '/admin/schemes'
    | '/admin/settings'
    | '/admin/users'
    | '/app/assistant'
    | '/app/crops'
    | '/app/disease'
    | '/app/farm'
    | '/app/fields'
    | '/app/history'
    | '/app/market'
    | '/app/notifications'
    | '/app/profile'
    | '/app/recommendations'
    | '/app/schemes'
    | '/app/settings'
    | '/app/weather'
    | '/admin/'
    | '/app/'
    | '/app/farm/$farmId'
    | '/app/farm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiModulesRoute: typeof AiModulesRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-modules': {
      id: '/ai-modules'
      path: '/ai-modules'
      fullPath: '/ai-modules'
      preLoaderRoute: typeof AiModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crops': {
      id: '/admin/crops'
      path: '/crops'
      fullPath: '/admin/crops'
      preLoaderRoute: typeof AdminCropsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disease': {
      id: '/admin/disease'
      path: '/disease'
      fullPath: '/admin/disease'
      preLoaderRoute: typeof AdminDiseaseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/farms': {
      id: '/admin/farms'
      path: '/farms'
      fullPath: '/admin/farms'
      preLoaderRoute: typeof AdminFarmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/markets': {
      id: '/admin/markets'
      path: '/markets'
      fullPath: '/admin/markets'
      preLoaderRoute: typeof AdminMarketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recommendations': {
      id: '/admin/recommendations'
      path: '/recommendations'
      fullPath: '/admin/recommendations'
      preLoaderRoute: typeof AdminRecommendationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schemes': {
      id: '/admin/schemes'
      path: '/schemes'
      fullPath: '/admin/schemes'
      preLoaderRoute: typeof AdminSchemesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crops': {
      id: '/app/crops'
      path: '/crops'
      fullPath: '/app/crops'
      preLoaderRoute: typeof AppCropsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/disease': {
      id: '/app/disease'
      path: '/disease'
      fullPath: '/app/disease'
      preLoaderRoute: typeof AppDiseaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/farm': {
      id: '/app/farm'
      path: '/farm'
      fullPath: '/app/farm'
      preLoaderRoute: typeof AppFarmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fields': {
      id: '/app/fields'
      path: '/fields'
      fullPath: '/app/fields'
      preLoaderRoute: typeof AppFieldsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market': {
      id: '/app/market'
      path: '/market'
      fullPath: '/app/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recommendations': {
      id: '/app/recommendations'
      path: '/recommendations'
      fullPath: '/app/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schemes': {
      id: '/app/schemes'
      path: '/schemes'
      fullPath: '/app/schemes'
      preLoaderRoute: typeof AppSchemesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/weather': {
      id: '/app/weather'
      path: '/weather'
      fullPath: '/app/weather'
      preLoaderRoute: typeof AppWeatherRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/farm/': {
      id: '/app/farm/'
      path: '/'
      fullPath: '/app/farm/'
      preLoaderRoute: typeof AppFarmIndexRouteImport
      parentRoute: typeof AppFarmRoute
    }
    '/app/farm/$farmId': {
      id: '/app/farm/$farmId'
      path: '/$farmId'
      fullPath: '/app/farm/$farmId'
      preLoaderRoute: typeof AppFarmFarmIdRouteImport
      parentRoute: typeof AppFarmRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCropsRoute: typeof AdminCropsRoute
  AdminDiseaseRoute: typeof AdminDiseaseRoute
  AdminFarmsRoute: typeof AdminFarmsRoute
  AdminMarketsRoute: typeof AdminMarketsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminRecommendationsRoute: typeof AdminRecommendationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSchemesRoute: typeof AdminSchemesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCropsRoute: AdminCropsRoute,
  AdminDiseaseRoute: AdminDiseaseRoute,
  AdminFarmsRoute: AdminFarmsRoute,
  AdminMarketsRoute: AdminMarketsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminRecommendationsRoute: AdminRecommendationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSchemesRoute: AdminSchemesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppFarmRouteChildren {
  AppFarmFarmIdRoute: typeof AppFarmFarmIdRoute
  AppFarmIndexRoute: typeof AppFarmIndexRoute
}

const AppFarmRouteChildren: AppFarmRouteChildren = {
  AppFarmFarmIdRoute: AppFarmFarmIdRoute,
  AppFarmIndexRoute: AppFarmIndexRoute,
}

const AppFarmRouteWithChildren =
  AppFarmRoute._addFileChildren(AppFarmRouteChildren)

interface AppRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppCropsRoute: typeof AppCropsRoute
  AppDiseaseRoute: typeof AppDiseaseRoute
  AppFarmRoute: typeof AppFarmRouteWithChildren
  AppFieldsRoute: typeof AppFieldsRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppMarketRoute: typeof AppMarketRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppSchemesRoute: typeof AppSchemesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWeatherRoute: typeof AppWeatherRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppCropsRoute: AppCropsRoute,
  AppDiseaseRoute: AppDiseaseRoute,
  AppFarmRoute: AppFarmRouteWithChildren,
  AppFieldsRoute: AppFieldsRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppMarketRoute: AppMarketRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppSchemesRoute: AppSchemesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWeatherRoute: AppWeatherRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AiModulesRoute: AiModulesRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
